# Generated by Django 4.1.2 on 2022-10-30 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teste', models.CharField(max_length=255, verbose_name='Cidade')),
                ('dia', models.DateTimeField(verbose_name='Dia do agedamento')),
                ('Tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicoagenda', to='Tecnico.tecnico', verbose_name='tecnico')),
            ],
        ),
    ]
