# Generated by Django 4.1.2 on 2022-10-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_remove_agenda_teste_agenda_empresa_agenda_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
