# Generated by Django 4.1.2 on 2022-10-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_agenda_disponivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='agenda',
            name='concluido',
            field=models.BooleanField(default=True, verbose_name='concluído'),
        ),
    ]
