# Generated by Django 4.1.2 on 2022-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_remove_agenda_disponivel_agenda_concluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='concluído'),
        ),
    ]
