# Generated by Django 4.1.2 on 2022-11-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_alter_agenda_concluido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='dia',
            new_name='data',
        ),
    ]
