# Generated by Django 4.1.2 on 2022-11-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Pagamento', '0002_pagamento_valor'),
        ('Empresa', '0002_alter_empresa_cnpj'),
        ('Tecnico', '0001_initial'),
        ('Agenda', '0006_alter_agenda_concluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cliente.cliente')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agenda.agenda')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.empresa')),
                ('pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pagamento.pagamento')),
                ('tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tecnico.tecnico')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Servico',
                'db_table': 'tutorial_servico',
            },
        ),
    ]
