# Generated by Django 4.1.2 on 2022-11-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnico', '0001_initial'),
        ('Cliente', '0001_initial'),
        ('Empresa', '0002_alter_empresa_cnpj'),
        ('Pagamento', '0002_pagamento_valor'),
        ('Servico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='pagamento',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='tecnico',
        ),
        migrations.AddField(
            model_name='servico',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienteservico', to='Cliente.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='servico',
            name='Empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresaservico', to='Empresa.empresa', verbose_name='empresa'),
        ),
        migrations.AddField(
            model_name='servico',
            name='Pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentoservico', to='Pagamento.pagamento', verbose_name='pagamento'),
        ),
        migrations.AddField(
            model_name='servico',
            name='Tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicoservico', to='Tecnico.tecnico', verbose_name='tecnico'),
        ),
    ]
