# Generated by Django 4.1.2 on 2022-11-04 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servico', '0002_remove_servico_cliente_remove_servico_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='Cliente',
        ),
    ]
