# Generated by Django 4.1.2 on 2022-11-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamento', '0002_pagamento_valor'),
        ('Cliente', '0001_initial'),
        ('Servico', '0004_remove_servico_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='Cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienteservico', to='Cliente.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='servico',
            name='Pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentoservico', to='Pagamento.pagamento', verbose_name='pagamento'),
        ),
    ]
