# Generated by Django 4.1.2 on 2022-11-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0006_alter_agenda_concluido'),
        ('Servico', '0005_servico_cliente_servico_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='Agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendaservico', to='Agenda.agenda', verbose_name='agenda'),
        ),
    ]
