# Generated by Django 4.1.2 on 2022-10-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.IntegerField(unique=True, verbose_name='CNPJ'),
        ),
    ]
