# Generated by Django 4.1.2 on 2022-10-31 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empresa', '0002_alter_empresa_cnpj'),
        ('Cliente', '0001_initial'),
        ('Tecnico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.CharField(max_length=100, verbose_name='Funcionario')),
                ('forma_de_pag', models.CharField(choices=[('cre', 'Crédito'), ('esp', 'Especie'), ('deb', 'Debito'), ('tra', 'Transferencia'), ('pix', 'Pix')], default='pix', max_length=100, verbose_name='Forma de pagamento')),
                ('Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientepagamento', to='Cliente.cliente', verbose_name='cliente')),
                ('Empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresapagamento', to='Empresa.empresa', verbose_name='empresa')),
                ('Tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicopagamento', to='Tecnico.tecnico', verbose_name='tecnico')),
                ('Veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veiculopagamento', to='Cliente.veiculo', verbose_name='veiculo')),
            ],
        ),
    ]
