# Generated by Django 4.1.2 on 2022-10-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.CharField(default=(59, 90), max_length=100, verbose_name='Valor pago'),
            preserve_default=False,
        ),
    ]
